name: thermohubclient

{% set python_version = os.environ.get("PY_VER", "3.7") %}

dependencies:
  - gxx_linux-64>=9.3.0  # [linux]
  - cmake>=3.7
  - ninja # [unix]
  - make  # [win]
  - git
  - ccache  # [unix]
  - pybind11
  - nlohmann_json
  - curl
  - velocypack
  - jsonarango>=0.3.0
  - pytest
  - python={{ python_version }}

environment:

  PYTHONPATH:
    - {{ root }}/artifacts/python/lib/python{{ python_version }}/site-packages   # [unix]
    - {{ root }}/build/lib/python{{ python_version }}/site-packages              # [unix]
    - {{ root }}/build/lib64/python{{ python_version }}/site-packages            # [unix]
    - {{ root }}\artifacts\python\Lib\site-packages                              # [win]
    - {{ root }}\build\lib\python{{ python_version }}\site-packages              # [win]

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]
